name: "Setup Node & pnpm"
description: "Install pnpm and setup Node.js with pnpm cache (fixed versions)"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js 20.12.0
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
      with:
        node-version: 20.12.0

    - name: Setup pnpm
      shell: bash
      run: npm install -g pnpm

    - name: Install Dependencies
      shell: bash
      run: pnpm i --frozen-lockfile --ignore-scripts
