name: Run Pinact

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pinact:
    name: pinact
    runs-on: ubuntu-latest
    timeout-minutes: 3

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Git
        uses: ./.github/actions/setup-git
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          origin: ${{ github.head_ref }}

      - name: Pin actions
        uses: suzuki-shunsuke/pinact-action@d735505f3decf76fca3fdbb4c952e5b3eba0ffdd # v0.1.2
